version: '{build}'
clone_folder: C:\projects\flow
os: Visual Studio 2015
platform: x64
environment:
  matrix:
    - ocaml_version: 4.02.1
      ocpwin_version: 4.02.1+ocp1-full-mingw64-20160113
      ocpwin_zip: C:\ocpwin64-20160113-4.02.1+ocp1-full-mingw64.zip
      ocpwin_uri: https://s3.amazonaws.com/ci-cache.flowtype.org/master/ocpwin/ocpwin64-20160113-4.02.1%2Bocp1-full-mingw64.zip
#    - ocaml_version: 4.01.0
#      ocpwin_version: 4.01.0+ocp1-full-mingw64-20160113
#      ocpwin_zip: C:\ocpwin64-20160113-4.01.0+ocp1-full-mingw64.zip
#      ocpwin_uri: http://www.ocamlpro.com/pub/ocpwin/ocpwin-builds/ocpwin64/20160113/ocpwin64-20160113-4.01.0+ocp1-full-mingw64.zip

install:
- ps: C:\projects\flow\resources\appveyor\install.ps1

build_script:
- ps: C:\projects\flow\resources\appveyor\build.ps1

test_script:
- ps: C:\projects\flow\resources\appveyor\test.ps1

after_build:
- ps: C:\projects\flow\resources\appveyor\after_build.ps1

artifacts:
  - path: bin\*.zip

deploy:
  provider: GitHub
  # flow-bot
  auth_token:
    secure: f1YgYz9csZ8QokY6+aXF10toZtXlFxicbm7uTcylqq+ILoRE6y5GUaf1TfoUalx5
  artifact: bin\*.zip
  on:
    appveyor_repo_tag: true
