---
permalink: /blog/:categories/:year/:month/:day/:title.html
url: http://flowtype.org
name: Flow
relative_permalinks: false
markdown: redcarpet
description: A static type checker for JavaScript
timezone: America/Los_Angeles

lsi: false
highlighter: pygments

paginate: 5
paginate_path: "/blog/page:num/"

flow:
  path: 'flow'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true
